// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import path from "node:path";
import fs from "node:fs";
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

const cwd = process.cwd();
for (const envPath of [
  path.resolve(cwd, ".env"),
  path.resolve(cwd, "apps", "api", ".env"),
]) {
  if (fs.existsSync(envPath)) {
    config({ path: envPath, override: true });
    break;
  }
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
